baseURL = "https://iccycling.github.io/hub/public/"
languageCode = "de-DE"
title = "ICCC Blog"
theme = "ananke"

relativeURLs = false   # Absolut ist für GitHub Pages am zuverlässigsten
canonifyURLs = true     # Macht alle Links sauber relativ zu baseURL
 
[pagination]
  disableAliases = true
  pagerSize = 4
  path = "page"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  author = "authors"

[caches]
  [caches.images]
    dir = ":cacheDir/images"
